on: [push]

name: CI

jobs:
  build_and_test:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    name: Rust project
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      # - run: cargo build --release --all-features
      - run: cargo run test_code/*.kry
